name: My Check
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
    test:
        # depends on lint action
        needs: [lint]
        strategy:
          matrix:
            version: [20, 22, 24]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                node-version: ${{ matrix.version }}
            - name: Install dependencies
              run: npm ci
            - name: Test
              run: npm run test
    secret:
        runs-on: ubuntu-latest
        steps:
            - name: Print secret
              run: echo "${{ secrets.TEST }}"